### ISSUE TITLE
Modify flask_debug from True to default as False

### ISSUE THREAD

**Issue by Jco04** [aws-samples/amazon-ecs-fargate-cdk-cicd#10]
Running Flask applications in debug mode results in the Werkzeug debugger being enabled. This includes a feature that allows arbitrary code execution. Documentation for both Flask [1] and Werkzeug [2] strongly suggests that debug mode should never be enabled on production systems.

[For More information see Bandit Documentation here](https://bandit.readthedocs.io/en/latest/plugins/b201_flask_debug_true.html)

**Comment by nvaidya1** [comment]
Thank you, merged your PR.
