### ISSUE TITLE
Getting exception in CodeBuild: no matching artifact paths found

### ISSUE THREAD

**Issue by anil1712** [aws-samples/amazon-ecs-fargate-cdk-cicd#13]
<html>
<body>

<html>
<body>

[Container] 2021/10/30 18:44:06 Running command pwd; ls -al; cat imagedefinitions.json
--
357 | /codebuild/output/src521779712
358 | total 16
359 | drwxr-xr-x 3 root root 4096 Oct 30 18:44 .
360 | drwxr-xr-x 7 root root 4096 Oct 30 18:42 ..
361 | -rw-r--r-- 1 root root  191 Oct 30 18:44 imagedefinitions.json
362 | drwxr-xr-x 7 root root 4096 Oct 30 18:42 src

</body>
</html>

[Container] 2021/10/30 18:44:06 Phase complete: POST_BUILD State: SUCCEEDED
--
365 | [Container] 2021/10/30 18:44:06 Phase context status code:  Message:
366 | [Container] 2021/10/30 18:44:07 Expanding base directory path: .
367 | [Container] 2021/10/30 18:44:07 Assembling file list
368 | [Container] 2021/10/30 18:44:07 Expanding .
369 | [Container] 2021/10/30 18:44:07 Expanding file paths for base directory .
370 | [Container] 2021/10/30 18:44:07 Assembling file list
371 | [Container] 2021/10/30 18:44:07 Expanding imagedefinitions.json
372 | [Container] 2021/10/30 18:44:07 Skipping invalid file path imagedefinitions.json
373 | [Container] 2021/10/30 18:44:07 Phase complete: UPLOAD_ARTIFACTS State: FAILED
374 | [Container] 2021/10/30 18:44:07 Phase context status code: CLIENT_ERROR Message: no matching artifact paths found

</body>
</html>

@nvaidya1 Please help me to get out of it.

**Comment by nvaidya1** [comment]
Hi @anil1712, thank you for letting us know & apologize for the late response. I have just recently merged a PR that updates the CDK packages and the whole workshop was tested end-end successfully by our contributor. I would request if you can please verify with the latest code if your workshop works well.
I am closing it for now, but please feel free to re-open OR open a new issue if you see any discrepancies.
